name: Build and publish to public ECR

on:
  push:
    # branches:
    #   - master
    #   - main
    #   - "[0-9]*"
    #   - "v[0-9]*"
    # tags:
    #   - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.PUBLIC_PUSH_ECR_AWS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PUBLIC_PUSH_ECR_AWS_SECRET }}
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v5
      with:
        images: public.ecr.aws/citizensadvice/clamav
        tags: type=sha

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: us-east-1 # ECR Public can only be logged into from the us-east-1 region.

    - name: ECR login
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
